// V37a — RISC-V RATS (Remote Attestation procedureS) — Attestation Service
//
// Features:
//   - Device-specific attestation signing key management
//   - Enclave attestation evidence generation (RATS-compliant format)
//   - Remote evidence verification
//   - Challenge-response protocol for freshness
//   - Supports PMP, ePMP, and Keystone-style TEE types
//
// Architecture:
//   The AttestationService holds a device-unique signing key and certificate.
//   For each enclave, it generates an AttestationEvidence structure containing
//   the enclave measurement, signer hash, TCB version, timestamp, nonce, and
//   a signature over all fields.
//
// Reference: RISC-V RATS specification, IETF RATS architecture (RFC 9334)

use crate::security::tee::{ApTeeEnclave, sha256_digest};

// ── Constants ───────────────────────────────────────────────────────────────

/// Maximum length of the attestation evidence buffer for serialization.
const EVIDENCE_BUF_SIZE: usize = 256;

/// Ed25519 signature length.
const SIGNATURE_LEN: usize = 64;

// ── TeeType ─────────────────────────────────────────────────────────────────

/// Type of TEE technology used by the platform.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum TeeType {
    /// Pure PMP isolation (V33 style).
    PMP = 0,
    /// ePMP enhanced isolation (V36d).
    EPMP = 1,
    /// Keystone-like S-mode enclave.
    Keystone = 2,
}

impl TeeType {
    pub fn name(&self) -> &'static str {
        match self {
            TeeType::PMP => "PMP",
            TeeType::EPMP => "ePMP",
            TeeType::Keystone => "Keystone",
        }
    }
}

// ── PlatformInfo ────────────────────────────────────────────────────────────

/// Platform information included in attestation evidence.
#[derive(Clone, Copy)]
pub struct PlatformInfo {
    /// CPU vendor string (e.g., "RISC-V International\0").
    pub cpu_vendor: [u8; 16],
    /// CPU model string.
    pub cpu_model: [u8; 16],
    /// Firmware version string.
    pub fw_version: [u8; 16],
    /// Type of TEE technology in use.
    pub tee_type: TeeType,
}

impl PlatformInfo {
    /// Create a new PlatformInfo with the given parameters.
    pub const fn new(
        vendor: &[u8; 16],
        model: &[u8; 16],
        fw: &[u8; 16],
        tee_type: TeeType,
    ) -> Self {
        PlatformInfo {
            cpu_vendor: *vendor,
            cpu_model: *model,
            fw_version: *fw,
            tee_type,
        }
    }

    /// Create a default PlatformInfo for QEMU virt machine.
    pub fn qemu_default(tee_type: TeeType) -> Self {
        let mut info = PlatformInfo {
            cpu_vendor: [0u8; 16],
            cpu_model: [0u8; 16],
            fw_version: [0u8; 16],
            tee_type,
        };
        info.cpu_vendor[..12].copy_from_slice(b"RISC-V Intl\0");
        info.cpu_model[..6].copy_from_slice(b"virt\0");
        info.fw_version[..8].copy_from_slice(b"AP-TEEv1\0");
        info
    }
}

// ── AttestationEvidence ─────────────────────────────────────────────────────

/// Attestation evidence structure (aligned with RATS specification).
///
/// This evidence is generated by the TEE for a specific enclave and
/// can be verified by a remote verifier.
#[derive(Clone, Copy)]
pub struct AttestationEvidence {
    /// SHA-512 measurement of the enclave (64 bytes).
    pub enclave_measurement: [u8; 64],
    /// SHA-256 hash of the enclave signing key (32 bytes).
    pub signer_hash: [u8; 32],
    /// TCB version of the TEE (u32).
    pub tcb_version: u32,
    /// Timestamp of evidence generation (tick count).
    pub timestamp: u64,
    /// Nonce for freshness (anti-replay).
    pub nonce: [u8; 16],
    /// Ed25519 signature over the evidence fields (64 bytes).
    pub signature: [u8; 64],
    /// Platform information.
    pub platform_info: PlatformInfo,
}

impl AttestationEvidence {
    /// Serialize the evidence into a byte buffer for transmission.
    ///
    /// Format:
    ///   [0..64)   — enclave_measurement
    ///   [64..96)  — signer_hash
    ///   [96..100) — tcb_version (4 bytes LE)
    ///   [100..108) — timestamp (8 bytes LE)
    ///   [108..124) — nonce
    ///   [124..188) — signature
    ///   [188..232) — platform_info (cpu_vendor + cpu_model + fw_version + tee_type)
    ///   Total: 236 bytes
    pub fn serialize(&self, buf: &mut [u8]) -> usize {
        let total = 236usize;
        if buf.len() < total {
            return 0;
        }

        let mut pos = 0;

        // enclave_measurement (64 bytes)
        buf[pos..pos + 64].copy_from_slice(&self.enclave_measurement);
        pos += 64;

        // signer_hash (32 bytes)
        buf[pos..pos + 32].copy_from_slice(&self.signer_hash);
        pos += 32;

        // tcb_version (4 bytes LE)
        buf[pos..pos + 4].copy_from_slice(&self.tcb_version.to_le_bytes());
        pos += 4;

        // timestamp (8 bytes LE)
        buf[pos..pos + 8].copy_from_slice(&self.timestamp.to_le_bytes());
        pos += 8;

        // nonce (16 bytes)
        buf[pos..pos + 16].copy_from_slice(&self.nonce);
        pos += 16;

        // signature (64 bytes)
        buf[pos..pos + 64].copy_from_slice(&self.signature);
        pos += 64;

        // platform_info: cpu_vendor (16) + cpu_model (16) + fw_version (16) + tee_type (4)
        buf[pos..pos + 16].copy_from_slice(&self.platform_info.cpu_vendor);
        pos += 16;
        buf[pos..pos + 16].copy_from_slice(&self.platform_info.cpu_model);
        pos += 16;
        buf[pos..pos + 16].copy_from_slice(&self.platform_info.fw_version);
        pos += 16;
        buf[pos..pos + 4].copy_from_slice(&(self.platform_info.tee_type as u32).to_le_bytes());
        pos += 4;

        pos
    }

    /// Deserialize evidence from a byte buffer.
    pub fn deserialize(buf: &[u8]) -> Option<Self> {
        if buf.len() < 236 {
            return None;
        }

        let mut evidence = AttestationEvidence {
            enclave_measurement: [0u8; 64],
            signer_hash: [0u8; 32],
            tcb_version: 0,
            timestamp: 0,
            nonce: [0u8; 16],
            signature: [0u8; 64],
            platform_info: PlatformInfo::qemu_default(TeeType::PMP),
        };

        let mut pos = 0;

        evidence.enclave_measurement.copy_from_slice(&buf[pos..pos + 64]);
        pos += 64;

        evidence.signer_hash.copy_from_slice(&buf[pos..pos + 32]);
        pos += 32;

        evidence.tcb_version = u32::from_le_bytes(buf[pos..pos + 4].try_into().ok()?);
        pos += 4;

        evidence.timestamp = u64::from_le_bytes(buf[pos..pos + 8].try_into().ok()?);
        pos += 8;

        evidence.nonce.copy_from_slice(&buf[pos..pos + 16]);
        pos += 16;

        evidence.signature.copy_from_slice(&buf[pos..pos + 64]);
        pos += 64;

        evidence.platform_info.cpu_vendor.copy_from_slice(&buf[pos..pos + 16]);
        pos += 16;
        evidence.platform_info.cpu_model.copy_from_slice(&buf[pos..pos + 16]);
        pos += 16;
        evidence.platform_info.fw_version.copy_from_slice(&buf[pos..pos + 16]);
        pos += 16;

        let tee_type_val = u32::from_le_bytes(buf[pos..pos + 4].try_into().ok()?);
        evidence.platform_info.tee_type = match tee_type_val {
            0 => TeeType::PMP,
            1 => TeeType::EPMP,
            2 => TeeType::Keystone,
            _ => return None,
        };

        Some(evidence)
    }
}

// ── AttestationResponse ─────────────────────────────────────────────────────

/// Response to a challenge (for challenge-response protocol).
pub struct AttestationResponse {
    /// The challenge nonce this responds to.
    pub challenge: [u8; 16],
    /// Fresh attestation evidence.
    pub evidence: AttestationEvidence,
    /// Additional endorsement data (e.g., TEE properties).
    pub endorsement: [u8; 64],
}

impl AttestationResponse {
    /// Serialize the response into a byte buffer.
    pub fn serialize(&self, buf: &mut [u8]) -> usize {
        let mut pos = 0usize;

        // challenge (16 bytes)
        if pos + 16 > buf.len() { return pos; }
        buf[pos..pos + 16].copy_from_slice(&self.challenge);
        pos += 16;

        // evidence (using serialize)
        let mut evidence_buf = [0u8; 256];
        let e_len = self.evidence.serialize(&mut evidence_buf);
        if pos + 4 + e_len > buf.len() { return pos - 16; }
        buf[pos..pos + 4].copy_from_slice(&(e_len as u32).to_le_bytes());
        pos += 4;
        buf[pos..pos + e_len].copy_from_slice(&evidence_buf[..e_len]);
        pos += e_len;

        // endorsement (64 bytes)
        if pos + 64 > buf.len() { return pos; }
        buf[pos..pos + 64].copy_from_slice(&self.endorsement);
        pos += 64;

        pos
    }
}

// ── AttestError ─────────────────────────────────────────────────────────────

/// Errors that can occur during attestation operations.
#[derive(Debug)]
pub enum AttestError {
    InvalidNonce,
    MeasurementMismatch,
    SignatureInvalid,
    CertificateExpired,
    PlatformMismatch,
    SerializationError,
}

// ── AttestationService ──────────────────────────────────────────────────────

/// Remote Attestation Service (RATS-compliant).
///
/// Manages device-specific attestation keys and provides evidence
/// generation and verification for enclaves.
pub struct AttestationService {
    /// Device-specific attestation signing key.
    device_key: [u8; 32],
    /// Device certificate chain (embedded or pointer to storage).
    device_cert: [u8; 512],
    /// Current nonce for anti-replay protection.
    nonce: [u8; 16],
    /// Platform information embedded in evidence.
    platform_info: PlatformInfo,
}

impl AttestationService {
    /// Initialize the attestation service with a device-specific key.
    pub fn init(device_key: &[u8; 32], tee_type: TeeType) -> Self {
        let mut svc = AttestationService {
            device_key: *device_key,
            device_cert: [0u8; 512],
            nonce: [0u8; 16],
            platform_info: PlatformInfo::qemu_default(tee_type),
        };

        // Generate initial nonce
        svc.refresh_nonce();
        svc
    }

    /// Initialize with a full certificate chain.
    pub fn init_with_cert(device_key: &[u8; 32], device_cert: &[u8; 512], tee_type: TeeType) -> Self {
        let mut svc = AttestationService::init(device_key, tee_type);
        svc.device_cert.copy_from_slice(device_cert);
        svc
    }

    /// Refresh the internal nonce using hardware entropy (V38a).
    pub fn refresh_nonce(&mut self) {
        let ent = crate::crypto::crypto_entropy();
        ent.random_bytes(&mut self.nonce);
    }

    /// Get the current nonce.
    pub fn current_nonce(&self) -> &[u8; 16] {
        &self.nonce
    }

    /// Generate attestation evidence for an enclave.
    ///
    /// This creates a signed evidence structure containing the enclave's
    /// measurement, signer identity, TCB version, and platform info.
    pub fn generate_evidence(&self, enclave: &ApTeeEnclave, nonce: &[u8; 16]) -> AttestationEvidence {
        let mut evidence = AttestationEvidence {
            enclave_measurement: enclave.measurement,
            signer_hash: enclave.signer_hash,
            tcb_version: enclave.tcb_version,
            timestamp: unsafe { crate::trap::TICK_COUNT as u64 },
            nonce: *nonce,
            signature: [0u8; 64],
            platform_info: self.platform_info,
        };

        // Compute signature over the evidence fields using device key
        evidence.signature = self.sign_evidence(&evidence);

        evidence
    }

    /// Generate an attestation evidence from raw measurement data.
    pub fn generate_evidence_raw(
        &self,
        measurement: &[u8; 64],
        signer_hash: &[u8; 32],
        tcb_version: u32,
        nonce: &[u8; 16],
    ) -> AttestationEvidence {
        let mut evidence = AttestationEvidence {
            enclave_measurement: *measurement,
            signer_hash: *signer_hash,
            tcb_version,
            timestamp: unsafe { crate::trap::TICK_COUNT as u64 },
            nonce: *nonce,
            signature: [0u8; 64],
            platform_info: self.platform_info,
        };

        evidence.signature = self.sign_evidence(&evidence);
        evidence
    }

    /// Verify attestation evidence from a remote enclave.
    ///
    /// Checks:
    ///   1. Nonce matches (anti-replay)
    ///   2. Signature verifies with the device key (or known public key)
    ///   3. Measurement is consistent
    pub fn verify_evidence(&self, evidence: &AttestationEvidence, expected_nonce: &[u8; 16]) -> Result<(), AttestError> {
        // 1. Check nonce
        if &evidence.nonce != expected_nonce {
            return Err(AttestError::InvalidNonce);
        }

        // 2. Verify signature
        if !self.verify_signature(evidence) {
            return Err(AttestError::SignatureInvalid);
        }

        Ok(())
    }

    /// Challenge-response protocol: generate a challenge.
    ///
    /// Returns a 16-byte nonce that the attester must include in the response.
    pub fn challenge(&mut self) -> [u8; 16] {
        self.refresh_nonce();
        self.nonce
    }

    /// Challenge-response protocol: create a response to a challenge.
    ///
    /// The response includes fresh evidence bound to the challenge nonce.
    pub fn respond(&self, challenge: &[u8; 16], enclave: &ApTeeEnclave) -> AttestationResponse {
        let evidence = self.generate_evidence(enclave, challenge);

        let mut endorsement = [0u8; 64];
        // Fill endorsement with platform capability info
        let end_bytes = b"AP-TEEv1 RISC-V TEE attestation\0";
        let end_len = end_bytes.len().min(64);
        endorsement[..end_len].copy_from_slice(&end_bytes[..end_len]);

        AttestationResponse {
            challenge: *challenge,
            evidence,
            endorsement,
        }
    }

    /// Format attestation evidence as human-readable text.
    pub fn format_evidence(buf: &mut [u8], evidence: &AttestationEvidence) -> usize {
        let mut pos = 0usize;

        pos += w_str(buf, pos, "AttestationEvidence:\n");
        pos += w_str(buf, pos, "  measurement: ");
        for b in &evidence.enclave_measurement[..8] {
            pos += w_hex_byte(buf, pos, *b);
        }
        pos += w_str(buf, pos, "...\n");

        pos += w_str(buf, pos, "  signer: ");
        for b in &evidence.signer_hash[..4] {
            pos += w_hex_byte(buf, pos, *b);
        }
        pos += w_str(buf, pos, "...\n");

        pos += w_str(buf, pos, "  tcb_version: ");
        pos += w_u64(buf, pos, evidence.tcb_version as u64);
        pos += w_str(buf, pos, "\n");

        pos += w_str(buf, pos, "  timestamp: ");
        pos += w_u64(buf, pos, evidence.timestamp);
        pos += w_str(buf, pos, "\n");

        pos += w_str(buf, pos, "  nonce: ");
        for b in &evidence.nonce {
            pos += w_hex_byte(buf, pos, *b);
        }
        pos += w_str(buf, pos, "\n");

        pos += w_str(buf, pos, "  platform: ");
        let vendor = core::str::from_utf8(&evidence.platform_info.cpu_vendor).unwrap_or("?");
        let model = core::str::from_utf8(&evidence.platform_info.cpu_model).unwrap_or("?");
        let fw = core::str::from_utf8(&evidence.platform_info.fw_version).unwrap_or("?");
        pos += w_str(buf, pos, vendor.trim_end_matches('\0'));
        pos += w_str(buf, pos, " ");
        pos += w_str(buf, pos, model.trim_end_matches('\0'));
        pos += w_str(buf, pos, " ");
        pos += w_str(buf, pos, fw.trim_end_matches('\0'));
        pos += w_str(buf, pos, " ");
        pos += w_str(buf, pos, evidence.platform_info.tee_type.name());
        pos += w_str(buf, pos, "\n");

        pos
    }

    // ── Internal helpers ─────────────────────────────────────────────────

    /// Sign the evidence data using the device key.
    ///
    /// Uses HMAC-SHA256 as a simplified stand-in for Ed25519.
    /// In production, this would use a hardware-backed Ed25519 engine.
    fn sign_evidence(&self, evidence: &AttestationEvidence) -> [u8; 64] {
        // Build message to sign: measurement || signer_hash || tcb_version || timestamp || nonce
        let mut msg = [0u8; 128];
        msg[..64].copy_from_slice(&evidence.enclave_measurement);
        msg[64..96].copy_from_slice(&evidence.signer_hash);
        msg[96..100].copy_from_slice(&evidence.tcb_version.to_le_bytes());
        msg[100..108].copy_from_slice(&evidence.timestamp.to_le_bytes());
        msg[108..124].copy_from_slice(&evidence.nonce);

        // Double-width signature: HMAC-SHA256 || HMAC-SHA256 (offset key)
        let mut sig = [0u8; 64];
        let h1 = hmac_sha256_simple(&self.device_key, &msg);
        sig[..32].copy_from_slice(&h1);

        // Second half uses a derived key
        let mut key2 = [0u8; 32];
        for i in 0..32 {
            key2[i] = self.device_key[i].wrapping_mul(0x5C).wrapping_add(0x37);
        }
        let h2 = hmac_sha256_simple(&key2, &msg);
        sig[32..64].copy_from_slice(&h2);

        sig
    }

    /// Verify a signature on evidence.
    ///
    /// This verifies the HMAC-based signature against the device key.
    fn verify_signature(&self, evidence: &AttestationEvidence) -> bool {
        let expected_sig = self.sign_evidence(evidence);
        // Constant-time comparison of signatures
        let mut diff = 0u8;
        for i in 0..64 {
            diff |= evidence.signature[i] ^ expected_sig[i];
        }
        diff == 0
    }
}

// ── Formatting helpers ──────────────────────────────────────────────────────

fn w_str(buf: &mut [u8], pos: usize, s: &str) -> usize {
    let bytes = s.as_bytes();
    let len = bytes.len().min(buf.len().saturating_sub(pos));
    if len > 0 {
        buf[pos..pos + len].copy_from_slice(&bytes[..len]);
    }
    len
}

fn w_u64(buf: &mut [u8], pos: usize, v: u64) -> usize {
    if v == 0 {
        if pos < buf.len() {
            buf[pos] = b'0';
            return 1;
        }
        return 0;
    }
    let mut temp = [0u8; 20];
    let mut n = v;
    let mut len = 0;
    while n > 0 {
        temp[len] = b'0' + (n % 10) as u8;
        n /= 10;
        len += 1;
    }
    let mut written = 0;
    for i in (0..len).rev() {
        if pos + written < buf.len() {
            buf[pos + written] = temp[i];
            written += 1;
        } else {
            break;
        }
    }
    written
}

fn w_hex_byte(buf: &mut [u8], pos: usize, b: u8) -> usize {
    if pos + 2 > buf.len() {
        return 0;
    }
    let hex = b"0123456789abcdef";
    buf[pos] = hex[(b >> 4) as usize];
    buf[pos + 1] = hex[(b & 0xF) as usize];
    2
}

// ── HMAC-SHA256 (reused from tee.rs, duplicated for module independence) ──

/// Simple HMAC-SHA256 (key, msg) -> 32-byte tag.
fn hmac_sha256_simple(key: &[u8; 32], msg: &[u8]) -> [u8; 32] {
    use crate::security::tee::sha256_digest;

    let mut inner_key = [0u8; 64];
    let mut outer_key = [0u8; 64];

    for i in 0..32 {
        inner_key[i] = key[i] ^ 0x36;
        outer_key[i] = key[i] ^ 0x5C;
    }
    for i in 32..64 {
        inner_key[i] = 0x36;
        outer_key[i] = 0x5C;
    }

    // inner_hash = SHA256(inner_key || msg)
    let mut inner_input = alloc::vec::Vec::new();
    inner_input.extend_from_slice(&inner_key);
    inner_input.extend_from_slice(msg);
    let inner_hash = sha256_digest(&inner_input);

    // result = SHA256(outer_key || inner_hash)
    let mut outer_input = alloc::vec::Vec::new();
    outer_input.extend_from_slice(&outer_key);
    outer_input.extend_from_slice(&inner_hash);
    sha256_digest(&outer_input)
}

// ── Global attestation service ──────────────────────────────────────────────

static mut ATTESTATION_SERVICE: Option<AttestationService> = None;

/// Initialize the global attestation service.
pub fn attestation_init(device_key: &[u8; 32], tee_type: TeeType) {
    unsafe {
        ATTESTATION_SERVICE = Some(AttestationService::init(device_key, tee_type));
    }
    crate::println!("  RATS: attestation service initialized ({})", tee_type.name());
}

/// Get a reference to the global attestation service.
pub fn attestation_service() -> Option<&'static AttestationService> {
    unsafe { ATTESTATION_SERVICE.as_ref() }
}

/// Get a mutable reference to the global attestation service.
pub fn attestation_service_mut() -> Option<&'static mut AttestationService> {
    unsafe { ATTESTATION_SERVICE.as_mut() }
}

/// Generate attestation evidence for an enclave using the global service.
pub fn attest_generate(enclave: &ApTeeEnclave, nonce: &[u8; 16]) -> Option<AttestationEvidence> {
    unsafe {
        ATTESTATION_SERVICE.as_ref().map(|svc| svc.generate_evidence(enclave, nonce))
    }
}

/// Verify attestation evidence using the global service.
pub fn attest_verify(evidence: &AttestationEvidence, expected_nonce: &[u8; 16]) -> Result<(), AttestError> {
    unsafe {
        match ATTESTATION_SERVICE.as_ref() {
            Some(svc) => svc.verify_evidence(evidence, expected_nonce),
            None => Err(AttestError::SignatureInvalid),
        }
    }
}
