core::arch::global_asm!(
    ".section .text.switch, \"ax\", @progbits",
    ".globl context_switch",
    ".align 2",
    "context_switch:",
    // a0 = *mut old TaskContext, a1 = *const new TaskContext
    "    sd ra, 0(a0)",
    "    sd sp, 8(a0)",
    "    sd s0, 16(a0)",
    "    sd s1, 24(a0)",
    "    sd s2, 32(a0)",
    "    sd s3, 40(a0)",
    "    sd s4, 48(a0)",
    "    sd s5, 56(a0)",
    "    sd s6, 64(a0)",
    "    sd s7, 72(a0)",
    "    sd s8, 80(a0)",
    "    sd s9, 88(a0)",
    "    sd s10, 96(a0)",
    "    sd s11, 104(a0)",
    // Save satp (page table root)
    "    csrr t0, satp",
    "    sd t0, 112(a0)",
    // Restore from new context
    "    ld ra, 0(a1)",
    "    ld sp, 8(a1)",
    "    ld s0, 16(a1)",
    "    ld s1, 24(a1)",
    "    ld s2, 32(a1)",
    "    ld s3, 40(a1)",
    "    ld s4, 48(a1)",
    "    ld s5, 56(a1)",
    "    ld s6, 64(a1)",
    "    ld s7, 72(a1)",
    "    ld s8, 80(a1)",
    "    ld s9, 88(a1)",
    "    ld s10, 96(a1)",
    "    ld s11, 104(a1)",
    // Restore satp (page table root) and flush TLB
    "    ld t0, 112(a1)",
    "    csrw satp, t0",
    "    sfence.vma zero, zero",
    "    fence.i",
    "    ret",
);

core::arch::global_asm!(
    ".section .text.trap_return, \"ax\", @progbits",
    ".globl user_trap_return",
    ".align 2",
    "user_trap_return:",
    // sp points to kernel stack top where TrapFrame is at sp-280.
    // Set sscratch for next trap entry
    "    addi t3, sp, 280",
    "    csrw sscratch, t3",
    // Load user_sp (will be restored to sp after all other regs)
    "    ld t0, 33*8(sp)",
    // Restore sepc, sstatus, satp
    "    ld t1, 30*8(sp)",
    "    csrw sepc, t1",
    "    ld t1, 31*8(sp)",
    "    csrw sstatus, t1",
    "    ld t1, 32*8(sp)",
    "    csrw satp, t1",
    "    sfence.vma zero, zero",
    // Restore all GPRs (skip t0 for user_sp)
    "    ld ra, 0*8(sp)",
    "    ld gp, 1*8(sp)",
    "    ld tp, 2*8(sp)",
    "    ld t1, 4*8(sp)",
    "    ld t2, 5*8(sp)",
    "    ld s0, 6*8(sp)",
    "    ld s1, 7*8(sp)",
    "    ld a0, 8*8(sp)",
    "    ld a1, 9*8(sp)",
    "    ld a2, 10*8(sp)",
    "    ld a3, 11*8(sp)",
    "    ld a4, 12*8(sp)",
    "    ld a5, 13*8(sp)",
    "    ld a6, 14*8(sp)",
    "    ld a7, 15*8(sp)",
    "    ld s2, 16*8(sp)",
    "    ld s3, 17*8(sp)",
    "    ld s4, 18*8(sp)",
    "    ld s5, 19*8(sp)",
    "    ld s6, 20*8(sp)",
    "    ld s7, 21*8(sp)",
    "    ld s8, 22*8(sp)",
    "    ld s9, 23*8(sp)",
    "    ld s10, 24*8(sp)",
    "    ld s11, 25*8(sp)",
    "    ld t3, 26*8(sp)",
    "    ld t4, 27*8(sp)",
    "    ld t5, 28*8(sp)",
    "    ld t6, 29*8(sp)",
    "    addi sp, sp, 280",
    "    mv sp, t0",              // sp = user_sp
    "    sret",
);

extern "C" {
    pub fn context_switch(old: *mut super::thread::TaskContext, new: *const super::thread::TaskContext);
}
